name: DEPLOYMENT 

on:
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: create delta-package
        run: |
          $pathsString = git diff origin/main origin/${{ github.head_ref }} --name-only force-app
          Write-Host $pathsString
          $pathArray = $pathsString.Split()

          mkdir delta-package

          $pathArray | ForEach{
              $destination = $_.Replace("force-app","delta-package")
              $temp =  $destination.Split("/")
              $destination = $destination.Replace("/"+$temp[$temp.Count-1],"")

              if (!(Test-Path -path $destination)) {New-Item $destination -Type Directory}
              Copy-Item $_ -Destination $destination
          }
      - name: authorization
        run: |
          New-Item -Name "server.key" -ItemType File -Value ${{ secrets.JWTKEYFILE }}
          sfdx force:auth:jwt:grant --setalias=MyOrg --jwtkeyfile server.key --clientid=${{ secrets.CONSUMERKEY }} --username=${{ secrets.USR }}
      - name: deployment
        run: |
          sfdx force:source:deploy --sourcepath delta-package -u MyOrg
       