name: DEPLOYMENT 

on:
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2

      - name: create delta-package
        run: |
          ls

          $pathsString = git diff main feature/feature-01 --name-only force-app
          Write-Host $pathsString
          $pathArray = $pathsString.Split()

          mkdir delta-package

          $pathArray | ForEach{
              Move-Item -Path $_ -Destination .\delta-package
          }

          ls delta-package