name: DEPLOYMENT 

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          FORMAT: json

      - name: Install Package dependencies
        run: |
          myArray = ("cat" "dog" "mouse" "frog")
          for str in ${myArray[@]}; do
            echo $str
          done