name: DEPLOYMENT 

on:
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: create delta-package
        run: |

          $pathsString = git diff origin/main origin/${{ github.head_ref }} --name-only force-app
          Write-Host $pathsString
          $pathArray = $pathsString.Split()

          mkdir delta-package

          $pathArray | ForEach{
              $destination = $_.Replace("force-app","delta-package")
              Write-host  $destination
              copy-item $_ $destination -Recurse -Force
          }

          ls delta-package
          ls delta-package\main
          ls delta-package\main\default
          ls delta-package\main\default\objects