name: DEPLOYMENT 

on:
  pull_request:
    branches: [self-hosted, windows, x64]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          FORMAT: json

      - name: 
        run: |
          $pathsString = ${{ env.GIT_DIFF }}
          $pathArray = $pathsString.Split()

          mkdir delta-package

          $pathArray | ForEach{
              Move-Item -Path $_ -Destination .\delta-package
          }

          ls delta-package