name: DEPLOYMENT 

on:
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6

      - name: create delta-package
        run: |
          $pathsString = ${{ env.GIT_DIFF }}
          $pathArray = $pathsString.Split()

          mkdir delta-package

          $pathArray | ForEach{
              Move-Item -Path $_ -Destination .\delta-package
          }

          ls delta-package