name: DEPLOYMENT 

on:
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: create delta-package
        run: |

          $pathsString = git diff origin/main origin/${{ github.head_ref }} --name-only force-app
          Write-Host $pathsString
          $pathArray = $pathsString.Split()

          mkdir delta-package

          $pathArray | ForEach{
              $destination = $_.Replace("force-app","delta-package")
              $temp =  $destination.Split("\")
              $destination = $destination.Replace("\"+$temp[$temp.Count-1],"")

              if (!(Test-Path -path $destination)) {New-Item $destination -Type Directory}
              Copy-Item $_ -Destination $destination
          }

      - name: deployment
        run: |
          sfdx force:source:deploy --sourcepath delta-package -u kamil.walo@cunning-fox-sfdga7.com
       